### ISSUE TITLE
Design and apply the appropriate scaffolding to operationalize the harvesting and ingest process.

### ISSUE THREAD

**Issue by htpvu** [rmap-project/rmap#70]
Scaffolding might include: possibly a registry of ingested DiSCO ID against source ID to support updates and avoid duplication. Possibly dockerize harvesting framework

**Comment by birkland** [comment]
The current harvester has [an internal registry](https://github.com/rmap-project/rmap-loader/tree/master/rmap-loader-deposit-disco#accounting) that it uses to avoid duplicates and updates.  Configuring it to use a "real" database like postgres is probably sufficient for operationalization in production.  Even better would be to record the provenance in the DiSCOs so that this could be done via search, and remove the need for a harvester to keep state

**Comment by karenhanson** [comment]
The [RMap Loader](https://github.com/rmap-project/rmap-loader) is a toolkit to support harvesting/ingest and fulfills this role.  The RMap-OSF loader uses these tools as scaffolding for harvester.
